version: '3.9'

services:

  httpd:
    build: .
    restart: unless-stopped
    env_file: ./.env
    expose:
      - 8080
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - mariadb
    volumes:
      - ./conf/observium:/conf:ro,Z
      - rrd-data:/opt/observium/rrd/
      - smokeping-data:/var/lib/smokeping/:ro,Z
      - smokeping-config:/etc/smokeping/config.d/
      - ../backup:/backup/destination
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      ofelia.enabled: "true"
      ofelia.job-exec.discover-all.schedule: "@every 6h"
      ofelia.job-exec.discover-all.no-overlap: "true"
      ofelia.job-exec.discover-all.user: "www-data"
      ofelia.job-exec.discover-all.command: "/bin/bash -c \"/opt/observium/observium-wrapper discovery -h all\""
      ofelia.job-exec.discover-new.schedule: "@every 5m"
      ofelia.job-exec.discover-new.no-overlap: "true"
      ofelia.job-exec.discover-new.user: "www-data"
      ofelia.job-exec.discover-new.command: "/bin/bash -c \"/opt/observium/observium-wrapper discovery --host new\""
      ofelia.job-exec.poll.schedule: "0 */5 * * * *"
      ofelia.job-exec.poll.no-overlap: "true"
      ofelia.job-exec.poll.user: "www-data"
      ofelia.job-exec.poll.command: "/bin/bash -c \"/opt/observium/observium-wrapper poller\""
      ofelia.job-exec.cleanup-logs.schedule: "0 13 5 * * *"
      ofelia.job-exec.cleanup-logs.user: "www-data"
      ofelia.job-exec.cleanup-logs.command: "/bin/bash -c \"/opt/observium/housekeeping.php -ysel\""
      ofelia.job-exec.cleanup-rrds.schedule: "0 47 4 * * *"
      ofelia.job-exec.cleanup-rrds.user: "www-data"
      ofelia.job-exec.cleanup-rrds.command: "/bin/bash -c \"/opt/observium/housekeeping.php -yrptb\""
      ofelia.job-exec.smokeping-config.schedule: "@every 5m"
      ofelia.job-exec.smokeping-config.command: "/bin/bash -c \"php /opt/observium/scripts/generate-smokeping.php > /etc/smokeping/config.d/Targets\""
      ofelia.job-exec.backup-rrd.schedule: "@daily"
      ofelia.job-exec.backup-rrd.command: "/bin/sh -c \"tar -czf /backup/destination/rrd_$(date '+%Y%m%d%H%M%S').tar.gz -C /backup/destination /opt/observium/rrd /var/lib/smokeping\""
      ofelia.job-exec.trim-backup-rrd.schedule: "@daily"
      ofelia.job-exec.trim-backup-rrd.command: "/bin/sh -c \"ls -t /backup/destination/rrd_*.gz | tail -n +10 | xargs rm -f\""
      traefik.enable: true
      traefik.http.routers.observium.rule: "Host(`${OBSERVIUM_FQDN}`)"
      traefik.http.routers.observium.entrypoints: "websecure"
      traefik.http.routers.observium.tls.certresolver: "letsencrypt"
    networks:
      - traefik
      - observium

  mariadb:
    image: mariadb:11
    container_name: observium-db
    restart: unless-stopped
    stop_grace_period: 45s
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 60s
      interval: 1m
      timeout: 5s
      retries: 3
    environment:
      TZ: ${TZ}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_MYSQL_LOCALHOST_USER: 1
    expose:
      - 3306
    volumes:
      - mariadb-data:/var/lib/mysql/
      - /run/mysqld:/var/run/mysqld/
      - ./conf/mariadb/:/etc/mysql/conf.d/:ro,Z
      - ../backup:/backup/destination
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup-db.schedule: "@daily"
      ofelia.job-exec.backup-db.command: "/bin/sh -c \"mariadb-dump --user ${DB_USER} -p${DB_PASSWORD} -h db -t ${DB_NAME} | gzip > /backup/destination/db_$(date '+%Y%m%d%H%M%S').sql.gz\""
      ofelia.job-exec.trim-backup-db.schedule: "@daily"
      ofelia.job-exec.trim-backup-db.command: "/bin/sh -c \"ls -t /backup/destination/db_*.gz | tail -n +10 | xargs rm -f\""
    networks:
      - observium

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker
    environment:
      TZ: ${TZ}
    depends_on:
      - httpd
      - mariadb
    security_opt:
      - label=disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
    networks:
      - observium

volumes:
  mariadb-data:
  rrd-data:

networks:
  traefik:
    external: true
  observium:
    external: false
