services:
  smokeping:
    build: .
    restart: unless-stopped
    depends_on:
      - httpd
    volumes:
      - smokeping-data:/var/lib/smokeping/
      - smokeping-config:/etc/smokeping/config.d/
    networks:
      - observium
    labels:
      com.centurylinklabs.watchtower.enable: "false"

