version: '3.9'

services:

  smokeping:
    build: .
    container_name: smokeping
    restart: unless-stopped
    depends_on:
      - httpd
    volumes:
      - smokeping-data:/var/lib/smokeping/
      - smokeping-config:/etc/smokeping/config.d/
    networks:
      - observium

