name: Docker image build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker_image_builds:
    strategy:
      matrix:
        images:
          - "httpd"
          - "smokeping"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker
      run: |
          curl -sSL https://get.docker.com/ | CHANNEL=stable sudo sh
          sudo service docker start
    - name: Build Docker Images
      run: |
        docker compose build ${image}
      env:
        image: ${{ matrix.images }}
