name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Observium image
      uses: docker/build-push-action@v3
      with:
        context: ./observium
        push: false
        tags: ${{ steps.prep.outputs.tags }}
        
